//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam_BasharJebry
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInfo
    {
        public int BusId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int NoOfSeats { get; set; }
    }
}
