//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam_BasharJebry
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABCTourDB_BasharJebryEntities1 : DbContext
    {
        public ABCTourDB_BasharJebryEntities1()
            : base("name=ABCTourDB_BasharJebryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusInfo> BusInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
